dynaconf_include = ['.secrets.api_keys.toml']

[markets]
interval = 3600 # seconds

[[markets.endpoints]]
api = 'binance'
channel = 'tickers_spot'
category = 'spot'
url = 'https://api.binance.com/api/v3/ticker/24hr'

[[markets.endpoints]]
api = 'binance'
channel = 'tickers_futures'
category = 'futures'
url = 'https://fapi.binance.com/fapi/v1/ticker/24hr' # need manually retrieving OI from /fapi/v1/openInterest

[[markets.endpoints]]
api = 'bybit'
channel = 'tickers_spot'
category = 'spot'
type = 'spot'
url = 'https://api.bybit.com/v5/market/tickers?category=spot'

[[markets.endpoints]]
api = 'bybit'
channel = 'tickers_futures'
category = 'linear'
type = 'linear'
url = 'https://api.bybit.com/v5/market/tickers?category=linear'

[[markets.endpoints]]
api = 'bybit'
channel = 'tickers_futures'
category = 'inverse'
url = 'https://api.bybit.com/v5/market/tickers?category=inverse'


#[[markets.endpoints]]
#api = 'okx'
#channel = 'tickers.spot'
#category = 'spot'
#url = 'https://www.okx.com/api/v5/market/tickers?instType=SPOT'

#[[markets.endpoints]]
#api = 'okx'
#channel = 'tickers.futures'
#category = 'futures'
#url = 'https://www.okx.com/api/v5/market/tickers?instType=SWAP'

[[markets.endpoints]]
api = 'okx'
channel = 'oi'
category = 'options'
url = 'https://www.okx.com/api/v5/public/open-interest?instType=OPTION'

[[markets.endpoints]]
api = 'okx'
channel = 'options'
category = 'summary'
url = 'https://www.okx.com/api/v5/public/opt-summary?uly=BTC-USD'

[[markets.endpoints]]
api = 'dydx'
channel = 'tickers_futures'
category = 'futures'
url = 'https://api.dydx.exchange/v3/markets'

[[markets.endpoints]]
api = 'deribit'
channel = 'tickers_futures'
category = 'futures'
url = 'https://www.deribit.com/api/v2/public/get_book_summary_by_currency?currency=BTC&kind=future'

[[markets.endpoints]]
api = 'deribit'
channel = 'tickers_options'
category = 'options'
url = 'https://www.deribit.com/api/v2/public/get_book_summary_by_currency?currency=BTC&kind=option'

[marketcap]
interval = 3600

[[marketcap.endpoints]]
api = 'coingecko'
channel = 'markets'
category = 'mcap'
url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=USD&order=market_cap_desc&per_page=200&page=1&sparkline=false&price_change_percentage=1h,24h&locale=en'

[[marketcap.endpoints]]
api = 'coingecko'
channel = 'derivatives'
category = 'derivatives'
url = 'https://api.coingecko.com/api/v3/derivatives'

[[marketcap.endpoints]]
api = 'coingecko'
channel = 'defi'
category = 'defi'
url = 'https://api.coingecko.com/api/v3/global/decentralized_finance_defi'

[[marketcap.endpoints]]
api = 'coingecko'
channel = 'global'
category = 'global'
url = 'https://api.coingecko.com/api/v3/global'

[[marketcap.endpoints]]
api = 'cmc'
channel = 'quotes'
category = 'quotes'
url = 'https://pro-api.coinmarketcap.com/v1/global-metrics/quotes/latest'
headers = { 'X-CMC_PRO_API_KEY' = "@format {this.cmc.api_key}" }

[[marketcap.endpoints]]
api = 'cmc'
channel = 'assets'
category = 'binance'
url = 'https://pro-api.coinmarketcap.com/v1/exchange/assets?id=270'
headers = { 'X-CMC_PRO_API_KEY' = "@format {this.cmc.api_key}" }

[[marketcap.endpoints]]
api = 'cmc'
channel = 'assets'
category = 'bitfinex'
url = 'https://pro-api.coinmarketcap.com/v1/exchange/assets?id=37'
headers = { 'X-CMC_PRO_API_KEY' = "@format {this.cmc.api_key}" }

[defi]
protocols = [
    'uniswap-v2',
    'uniswap-v3',
    'curve-dex',
    'kine-finance',
    'venus',
    'aave-v3',
    'pancakeswap',
]
interval = 3600

[[defi.endpoints]]
api = 'defillama'
channel = 'defi_tvl'
category = 'tvl'
url = 'https://api.llama.fi/v2/chains'

[[defi.endpoints]]
api = 'defillama'
channel = 'defi_stablecoins'
category = 'stablecoins'
url = 'https://stablecoins.llama.fi/stablecoins?includePrices=true'

[[defi.endpoints]]
api = 'defillama'
channel = 'defi_yields'
category = 'yields'
url = 'https://yields.llama.fi/pools'
interval = 28800

[[defi.endpoints]]
api = 'defillama'
channel = 'defi_fees'
category = 'fees'
url = 'https://api.llama.fi/overview/fees?excludeTotalDataChart=true&excludeTotalDataChartBreakdown=true&dataType=dailyFees'

[etf]
tickers = [
    'BITB',
    'HODL',
    'GBTC',
    'FBTC',
    'IBIT',
    'EZBC',
    'ARKB',
    'BTCO',
    'DEFI',
    'BTCW',
    'BRRR',
]
bloomberg_ticker_postfix = ' Us Equity'
fields = ['PX_LAST', 'FUND_TOTAL_ASSETS']
