dynaconf_include = ['.secrets.api_keys.toml']

[markets]
interval = 900

[[markets.endpoints]]
api = 'binance'
channel = 'tickers.spot'
url = 'https://api.binance.com/api/v3/ticker/24hr'

[[markets.endpoints]]
api = 'binance'
channel = 'tickers.futures'
type = 'linear'
url = 'https://fapi.binance.com/fapi/v1/ticker/24hr' # need manually retrieving OI from /fapi/v1/openInterest

[[markets.endpoints]]
api = 'bybit'
channel = 'tickers.spot'
type = 'spot'
url = 'https://api.bybit.com/v5/market/tickers?category=spot'

[[markets.endpoints]]
api = 'bybit'
channel = 'tickers.linear'
type = 'linear'
url = 'https://api.bybit.com/v5/market/tickers?category=linear'

[[markets.endpoints]]
api = 'bybit'
channel = 'tickers.inverse'
url = 'https://api.bybit.com/v5/market/tickers?category=inverse'

[[markets.endpoints]]
api = 'okx'
channel = 'tickers.spot'
url = 'https://www.okx.com/api/v5/market/tickers?instType=SPOT'

[[markets.endpoints]]
api = 'okx'
channel = 'tickers.swap'
url = 'https://www.okx.com/api/v5/market/tickers?instType=SWAP'

[[markets.endpoints]]
api = 'okx'
channel = 'oi.option'
url = 'https://www.okx.com/api/v5/public/open-interest?instType=OPTION'

[[markets.endpoints]]
api = 'okx'
channel = 'options'
url = 'https://www.okx.com/api/v5/public/opt-summary?uly=BTC-USD'

[[markets.endpoints]]
api = 'dydx'
channel = 'tickers'
url = 'https://api.dydx.exchange/v3/markets'

[[markets.endpoints]]
api = 'deribit'
channel = 'book.future'
url = 'https://www.deribit.com/api/v2/public/get_book_summary_by_currency?currency=BTC&kind=future'

[[markets.endpoints]]
api = 'deribit'
channel = 'book.option'
url = 'https://www.deribit.com/api/v2/public/get_book_summary_by_currency?currency=BTC&kind=option'

[marketcap]
interval = 3600

[[marketcap.endpoints]]
api = 'coingecko'
channel = 'markets'
url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=USD&order=market_cap_desc&per_page=100&page=1&sparkline=false&locale=en'

[[marketcap.endpoints]]
api = 'coingecko'
channel = 'derivatives'
url = 'https://api.coingecko.com/api/v3/derivatives'

[[marketcap.endpoints]]
api = 'coingecko'
channel = 'defi'
url = 'https://api.coingecko.com/api/v3/global/decentralized_finance_defi'

[[marketcap.endpoints]]
api = 'coingecko'
channel = 'global'
url = 'https://api.coingecko.com/api/v3/global'

[[marketcap.endpoints]]
api = 'cmc'
channel = 'quotes'
url = 'https://pro-api.coinmarketcap.com/v1/global-metrics/quotes/latest'
headers = { 'X-CMC_PRO_API_KEY' = "@format {this.cmc.api_key}" }

[[marketcap.endpoints]]
api = 'cmc'
channel = 'assets.binance'
url = 'https://pro-api.coinmarketcap.com/v1/exchange/assets?id=270'
headers = { 'X-CMC_PRO_API_KEY' = "@format {this.cmc.api_key}" }

[[marketcap.endpoints]]
api = 'cmc'
channel = 'assets.coinbase'
url = 'https://pro-api.coinmarketcap.com/v1/exchange/assets?id=89'
headers = { 'X-CMC_PRO_API_KEY' = "@format {this.cmc.api_key}" }

[defi]
protocols = [
    'uniswap-v2',
    'uniswap-v3',
    'curve-dex',
    'kine-finance',
    'venus',
    'aave-v3',
    'pancakeswap',
]

[[defi.endpoints]]
api = 'defillama'
channel = 'tvl'
url = 'https://api.llama.fi/v2/chains'
interval = 900

[[defi.endpoints]]
api = 'defillama'
channel = 'stablecoins'
url = 'https://stablecoins.llama.fi/stablecoins?includePrices=true'
interval = 900

[[defi.endpoints]]
api = 'defillama'
channel = 'yields'
url = 'https://yields.llama.fi/pools'
interval = 900

[[defi.endpoints]]
api = 'defillama'
channel = 'fees'
url = 'https://api.llama.fi/overview/fees?excludeTotalDataChart=true&excludeTotalDataChartBreakdown=true&dataType=dailyFees'
interval = 900

[etf]
tickers = [
    'BITB',
    'HODL',
    'GBTC',
    'FBTC',
    'IBIT',
    'EZBC',
    'ARKB',
    'BTCO',
    'DEFI',
    'BTCW',
    'BRRR',
]
bloomberg_ticker_postfix = ' Us Equity'
fields = ['PX_LAST', 'FUND_TOTAL_ASSETS']
