[markets]
interval = 900

[[markets.endpoints]]
exchange = 'binance'
channel = 'tickers'
url = 'https://api.binance.com//api/v3/ticker/24hr'

[[markets.endpoints]]
exchange = 'binance'
channel = 'tickers'
url = 'https://fapi.binance.com///fapi/v1/ticker/24hr' # need manually retrieving OI from /fapi/v1/openInterest

[[markets.endpoints]]
exchange = 'bybit'
channel = 'tickers'
url = 'https://api.bybit.com/v5/market/tickers?category=spot'

[[markets.endpoints]]
exchange = 'bybit'
channel = 'tickers'
url = 'https://api.bybit.com/v5/market/tickers?category=linear'

[[markets.endpoints]]
exchange = 'bybit'
channel = 'tickers'
url = 'https://api.bybit.com/v5/market/tickers?category=inverse'

[[markets.endpoints]]
exchange = 'okx'
channel = 'tickers'
url = 'https://www.okx.com/api/v5/market/tickers?instType=SPOT'

[[markets.endpoints]]
exchange = 'okx'
channel = 'tickers'
url = 'https://www.okx.com/api/v5/market/tickers?instType=SWAP'

[[markets.endpoints]]
exchange = 'okx'
channel = 'tickers'
url = 'https://www.okx.com/api/v5/public/open-interest?instType=OPTION'

[[markets.endpoints]]
exchange = 'okx'
channel = 'tickers'
url = 'https://www.okx.com/api/v5/public/opt-summary?uly=BTC-USD'

[[markets.endpoints]]
exchange = 'dydx'
channel = 'tickers'
url = 'https://api.dydx.exchange//v3/markets'

[[markets.endpoints]]
exchange = 'deribit'
channel = 'options1'
url = 'https://www.deribit.com/api/v2/public/get_book_summary_by_currency?currency=BTC&kind=future'

[[markets.endpoints]]
exchange = 'deribit'
channel = 'options1'
url = 'https://www.deribit.com/api/v2/public/get_book_summary_by_currency?currency=BTC&kind=option'

[[markets.endpoints]]
exchange = 'deribit'
channel = 'options2'
url = 'https://www.deribit.com/api/v2/public/ticker?instrument_name=BTC-PERPETUAL' # Needs individual calls for futures and options

[defillama.tvl]
endpoint = 'https://api.llama.fi/tvl/'
protocols = [
    'uniswap-v2',
    'uniswap-v3',
    'curve-dex',
    'kine-finance',
    'venus',
    'aave-v3',
    'pancakeswap',
]
interval = 3600

[defillama.fees]
endpoint3 = 'https://api.llama.fi/overview/fees'

[marketcap]

[[marketcap.endpoints]]
api = 'coingecko'
channel = 'markets'
url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=USD&order=market_cap_desc&per_page=100&page=1&sparkline=false&locale=en'

[[marketcap.endpoints]]
api = 'coingecko'
channel = 'markets'
url = 'https://api.coingecko.com/api/v3/derivatives'

[[marketcap.endpoints]]
api = 'coingecko'
channel = 'markets'
url = 'https://api.coingecko.com/api/v3/global'

[[marketcap.endpoints]]
api = 'coinmarketcap'
channel = 'markets'
url = 'https://pro-api.coinmarketcap.com/v1/global-metrics/quotes/latest'

[[marketcap.endpoints]]
api = 'coinmarketcap'
channel = 'markets'
url = 'https://pro-api.coinmarketcap.com/v1/blockchain/statistics/latest'

[[marketcap.endpoints]]
api = 'coinmarketcap'
channel = 'markets'
url = 'https://pro-api.coinmarketcap.com/v1/exchange/assets'
